# Generated by Django 2.1.1 on 2018-09-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery'),
        ),
    ]
