# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-27 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0006_auto_20180926_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='galleries.Image'),
        ),
    ]
