# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-28 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0007_vote_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
